/**
 * Supplementary guards for the on-foot wildlife loop. The fixed P5 catalogs
 * (`FLORA`/`FAUNA`/`floraForBiome`/`faunaForBiome`) are gone (cascade tier 5b);
 * wild life is generated by the genome now. This suite keeps the
 * catalog-independent invariants (scavenge never yields an animal part, explore
 * thresholds, combat boundaries) and migrates the "every biome is inhabited"
 * coverage to the genome: a region always has flora, fauna are commonly found,
 * and what's found varies region-to-region (env-fit + combinatorial).
 */
import { describe, it, expect } from "vitest";
import {
  regionFlora,
  regionFauna,
  speciesDrop,
  systemAt,
  regionGrid,
  regionIndex,
} from "@/lib/universe";
import { isMaterialId, SCAVENGEABLE, pickScavenge } from "@/lib/game/materials";
import { exploreOutcome, combatRound, speciesCombatStats } from "@/lib/game/rules";

const SEED = "omniplex-prod-1";

/** Collect several distinct rocky regions for genome sampling. */
function sampleRockyRegions(limit: number) {
  const out: { galaxy: number; arm: number; cluster: number; system: number; planet: number; region: number }[] = [];
  for (let c = 40; c < 64 && out.length < limit; c++)
    for (let s = 0; s < 120 && out.length < limit; s++)
      for (const p of systemAt(SEED, { galaxy: 0, arm: 0, cluster: c, system: s }).planets) {
        if (p.isGas || p.regionCount < 400) continue;
        const { rows, cols } = regionGrid(p);
        // A handful of cells spread across latitudes (varied biomes/climate).
        for (const lat of [0, Math.floor(rows / 2), rows - 1]) {
          out.push({ ...p.coord, region: regionIndex(lat, Math.floor(cols / 2), cols) });
          if (out.length >= limit) break;
        }
        if (out.length >= limit) break;
      }
  if (out.length === 0) throw new Error("no rocky regions");
  return out;
}

describe("genome wildlife coverage", () => {
  const regions = sampleRockyRegions(30);

  it("every sampled region has at least one flora (the web's base is never empty)", () => {
    for (const r of regions) {
      expect(regionFlora(SEED, r).length, `flora at ${JSON.stringify(r)}`).toBeGreaterThan(0);
    }
  });

  it("fauna are commonly found across regions", () => {
    const withFauna = regions.filter((r) => regionFauna(SEED, r).length > 0).length;
    expect(withFauna).toBeGreaterThan(0);
  });

  it("what's found varies region-to-region (combinatorial, env-fit)", () => {
    const signatures = new Set(
      regions.map((r) =>
        [...regionFlora(SEED, r), ...regionFauna(SEED, r)]
          .map((sp) => `${sp.archetype}:${Object.values(sp.traits).join(",")}`)
          .join("|"),
      ),
    );
    // The vast majority of regions should yield a distinct ecology.
    expect(signatures.size).toBeGreaterThan(regions.length / 2);
  });

  it("every generated drop points at a real bounded material", () => {
    for (const r of regions) {
      for (const sp of [...regionFlora(SEED, r), ...regionFauna(SEED, r)]) {
        const d = speciesDrop(sp);
        expect(isMaterialId(d.materialId)).toBe(true);
        expect(d.qty).toBeGreaterThan(0);
      }
    }
  });
});

describe("scavenging", () => {
  it("only ever yields scavengeable (never animal) materials", () => {
    for (const m of SCAVENGEABLE) expect(m.category).not.toBe("animal");
    for (let i = 0; i < 100; i++) {
      const m = pickScavenge(i / 100);
      expect(m.category).not.toBe("animal");
      expect(SCAVENGEABLE).toContain(m);
    }
  });

  it("low rolls turn up the rare relics", () => {
    expect(pickScavenge(0).category).toBe("relic");
  });
});

describe("explore thresholds + combat boundaries", () => {
  it("partitions the roll range in scavenge<flora<fauna order", () => {
    expect(exploreOutcome(0)).toBe("scavenge");
    expect(exploreOutcome(0.5)).toBe("flora");
    expect(exploreOutcome(0.99)).toBe("fauna");
  });

  it("combatRound never returns negative HP", () => {
    const r = combatRound({ playerHp: 1, playerAtk: 1, creatureHp: 1, creatureAtk: 1000 });
    expect(r.playerHp).toBe(0);
    expect(r.creatureHp).toBe(0);
    expect(r.playerDead).toBe(true);
    expect(r.creatureDead).toBe(true);
  });

  it("speciesCombatStats feeds the same combatRound machinery", () => {
    const grazer: any = {
      archetype: "grazer",
      trophicRole: "herbivore",
      traits: { size: "small", defense: "none", temperament: "skittish" },
      diet: [],
    };
    const stats = speciesCombatStats(grazer);
    const round = combatRound({
      playerHp: 100,
      playerAtk: 12,
      creatureHp: stats.maxHp,
      creatureAtk: stats.attack,
    });
    expect(round.creatureHp).toBe(Math.max(0, stats.maxHp - 12));
    expect(round.playerHp).toBe(Math.max(0, 100 - stats.attack));
  });
});
