/**
 * Public API of the procedural universe generator.
 *
 * Every gameplay system reads from here. `command-core` imports `systemAt`,
 * `planetAt`, `planetKey`, `warpDistance`, and the `RESOURCES` catalog; keep
 * these signatures stable. See `CLAUDE.md` §"Conventions" for the
 * load-bearing decisions established by this module.
 */

export { RESOURCES, getResource, mineralsForBiome, isBiomeSpecific } from "./resources";
export type { Resource, ResourceId } from "./resources";

export {
  BIOMES,
  ATMOSPHERES,
  STAR_CLASSES,
  SITE_TYPES,
  SIZE_CLASSES,
  SIZE_CLASS_LABELS,
  REGION_FORMATIONS,
  FORMATION_LABELS,
  FORMATION_TENDENCY,
  GAS_RADIUS_THRESHOLD,
  MAX_PLANETS,
  REGION_COUNT_MIN,
  REGION_COUNT_MAX,
  PALETTE_MIN,
  PALETTE_MAX,
  ARM_COUNT_MIN,
  ARM_COUNT_MAX,
} from "./types";
export type {
  Biome,
  Atmosphere,
  StarClass,
  SiteType,
  Site,
  SizeClass,
  RegionFormation,
  SystemCoord,
  ClusterCoord,
  StarPosition,
  PlanetCoord,
  RegionCoord,
  ResourceDeposit,
  Planet,
  Region,
  StarSystem,
  Galaxy,
} from "./types";
export type { Direction } from "./gen";

export {
  galaxyAt,
  systemAt,
  planetAt,
  regionAt,
  regionGrid,
  regionCoords,
  regionIndex,
  moveRegion,
  siteAt,
  siteLoot,
  SITE_SPAWN_CHANCE,
  orbitalSiteAt,
  orbitalSiteLoot,
  ORBITAL_SITE_SPAWN_CHANCE,
  startingWorld,
  randomStartingWorld,
  SPAWN_CLUSTER,
  clusterStars,
  clusterOf,
  systemPosition,
  systemFromPosition,
  STARS_PER_CLUSTER,
  STAR_CLUSTER_SIGMA,
  STAR_CLUSTER_MAX_RADIUS,
  systemKey,
  planetKey,
  regionKey,
  parseLocationKey,
  warpDistance,
  atmosphereDensity,
  biomeTempOffset,
  biomeHazardOffset,
  HABITABLE_BIOMES,
  hasSettlement,
  systemOutpostPlanets,
  hasOutpost,
  TEMP_MIN,
  TEMP_MAX,
  SYSTEM_SPAN,
  CLUSTER_RING_SPAN,
  CLUSTER_R0,
  MAX_CLUSTERS_PER_ARM,
  RADIATION_MAX,
  RAD_HAZARD_FLOOR_MAX,
  armAngle,
  clusterRadius,
  clusterCenter,
  galacticRadiation,
  radiationHazardFloor,
} from "./gen";
